// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pooled — used by the running app for all queries.
    // Note: Prisma 7's config-based `datasource` has no `directUrl` field
    // (that was a schema.prisma-only concept in earlier Prisma versions).
    // DIRECT_URL (port 5432) is still used, but only by the manual migration
    // workaround script — see postgresql-prisma-setup.md "Known Issue" section.
    url: process.env["DATABASE_URL"],
  },
});
